# Generated by Django 3.1 on 2020-08-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motosellapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='rodzaj_paliwa',
            field=models.CharField(choices=[('benzyna', 'benzyna'), ('diesel', 'diesel'), ('LPG', 'LPG')], default='benzyna', max_length=32),
        ),
    ]
