# Generated by Django 3.1 on 2020-08-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motosellapp', '0003_auto_20200809_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='zdjecie',
            field=models.ImageField(blank=True, upload_to='zdjecia'),
        ),
    ]
