# Generated by Django 3.1 on 2020-08-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motosellapp', '0004_auto_20200809_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='zdjecie',
            field=models.ImageField(upload_to='zdjecia'),
        ),
    ]
