# Generated by Django 3.1 on 2020-08-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motosellapp', '0006_auto_20200809_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='zdjecie',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
