# Generated by Django 3.1 on 2020-08-10 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motosellapp', '0009_auto_20200810_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='zdjecie',
            field=models.ImageField(upload_to='media'),
        ),
    ]
