# Generated by Django 3.1 on 2020-08-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motosellapp', '0012_auto_20200810_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='zdjecie',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
