# Generated by Django 3.1 on 2020-08-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motosellapp', '0013_auto_20200810_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='zdjecie',
            field=models.ImageField(default='default.png', upload_to='media'),
        ),
    ]
