# Generated by Django 3.1 on 2020-08-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motosellapp', '0014_auto_20200811_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='zdjecie',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
