# Generated by Django 3.1 on 2020-08-12 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motosellapp', '0015_auto_20200811_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='status',
            field=models.CharField(choices=[('aktualny', 'aktualny'), ('nieaktualny', 'nieaktualny')], default='aktualny', max_length=32),
        ),
    ]
