# Generated by Django 3.1 on 2020-08-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motosellapp', '0018_oferta_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='kontakt',
            field=models.CharField(default=123456789, max_length=9),
        ),
        migrations.AddField(
            model_name='oferta',
            name='koszt',
            field=models.CharField(default=10000, max_length=20),
        ),
    ]
