# Generated by Django 3.1 on 2020-08-13 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motosellapp', '0020_auto_20200812_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='kontakt',
            field=models.IntegerField(default=123456789, max_length=9),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='koszt',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='pojemnosc_skokowa',
            field=models.IntegerField(),
        ),
    ]
